#-------------------------------
# General Site Settings
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://paul-song-minerva.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "portfolio/blog/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /portfolio/:name
  posts:
    output: true
    permalink: /portfolio/:slug
  authors:
    output: true
    permalink: /portfolio/:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"


sass:
  sass_dir: _sass
  style: compressed

# # For GitHub page
# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge